spring:
  application:
    name: gateway_service
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
#      routes:
#      - id: rest_service_route
#        uri: lb://rest_service
#        predicates:
#        - Path=/rest-service/**
#        filters:
#        - RewritePath=/rest-service/(?<path>.*), /$\{path}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9080/eureka
